### PR TITLE
Standardization

### LINKED ISSUE #13: Incorrect input parameter "sensitive_system"
The actual parameter name is "is_sensitive_system".  Readme.md is listing all references to this parameter as "sensitive_system" including the example.

### PR DESCRIPTION
**Pull request by karikarshivani**
### [Report](https://github.com/karikarshivani/InSpecReports/blob/master/Standardization/Windows10_Before.json) before changes
---
**Questions for @ejaronne:**
- [x] README - [model](https://github.com/mitre/docs-mitre-inspec/blob/master/templates/baseline_readme.md)
- [x] in inspec.yml, validate the title and the summary to be consistent
- [x] in inspec.yml, set `inspec_version: ">= 4.0"`
- [x] in inspec.yml, validate if any supports statements are valid
- [x] in inspec.yml, change from attributes to inputs
- [x] in inspec.yml, set `sensitive: ` flags as appropriate, e.g., for user names, passwords, hostnames, etc.
- [x] Update the License.md
---
### [Report](https://github.com/karikarshivani/InSpecReports/blob/master/Standardization/Windows10_After.json) after changes

Closes #13

### CODE REVIEW

**Comment by karikarshivani** [comment]
@ejaronne There are some example jsons and ymls in the repo, should I move them to an "examples" folder like some other profiles?

**Review by aaronlippold — APPROVED** [review]

**Comment by karikarshivani** [comment]
> @ejaronne There are some example jsons and ymls in the repo, should I move them to an "examples" folder like some other profiles?

I've organized them as per this comment for reference.

**Comment by karikarshivani** [comment]
ReportComparison

**Comment by karikarshivani** [comment]
Fixes #13

**Pull request merged**
